# Manages the nightly.eclipse-pass.org deploy
# `docker-compose -f eclipse-pass.base.yml -f eclipse-pass.nightly.yml up`
version: '3.8'

services:
  auth:
    env_file: .eclipse-pass.nightly_env

  pass-core:
    env_file: .eclipse-pass.nightly_env
    image: ghcr.io/eclipse-pass/pass-core-main:0.2.0-SNAPSHOT@sha256:ee786c4f484617f3c0f0eea5957e660e31821c645acb1f63b4f6cf5dc9e3ed0c

  pass-ui:
    env_file: .eclipse-pass.nightly_env

  postgres:
    env_file: .eclipse-pass.nightly_env

  pass-ui-public:
    env_file: .eclipse-pass.nightly_env

  idp:
    environment:
      - IDP_HOST=https://nightly.eclipse-pass.org

  loader:
    env_file: .eclipse-pass.nightly_env
