# Manages the nightly.eclipse-pass.org deploy
# `docker-compose -f eclipse-pass.base.yml -f eclipse-pass.nightly.yml up`
version: '3.8'

services:
  auth:
    env_file:
      - .eclipse-pass.nightly_env

  pass-core:
    image: ghcr.io/eclipse-pass/pass-core-main:0.3.0-SNAPSHOT@sha256:5403a4757d95ca71ef62a5b6fa3a82ee176c36e28cb89fda4c71271d56dd5fb5
    env_file:
      - .eclipse-pass.nightly_env

  pass-ui:
    env_file:
      - .eclipse-pass.nightly_env

  postgres:
    env_file:
      - .eclipse-pass.nightly_env

  pass-ui-public:
    env_file:
      - .eclipse-pass.nightly_env

  idp:
    env_file:
      - .eclipse-pass.nightly_env

  loader:
    env_file:
      - .eclipse-pass.nightly_env
