# Manages the nightly.eclipse-pass.org deploy
# `docker-compose -f eclipse-pass.base.yml -f eclipse-pass.nightly.yml up`
version: '3.8'

services:
  auth:
    env_file: .eclipse-pass.nightly_env

  pass-core:
    env_file: .eclipse-pass.nightly_env
    image: ghcr.io/eclipse-pass/pass-core-main:0.2.0-SNAPSHOT@sha256:a3817abfebcce09b354ac90d50cc32dfc3bc5f82599e055a40666ad5614a8319

  pass-ui:
    env_file: .eclipse-pass.nightly_env

  postgres:
    env_file: .eclipse-pass.nightly_env

  pass-ui-public:
    env_file: .eclipse-pass.nightly_env

  idp:
    environment:
      - IDP_HOST=https://nightly.eclipse-pass.org

  loader:
    env_file: .eclipse-pass.nightly_env
