# Manages the nightly.eclipse-pass.org deploy
# `docker-compose -f eclipse-pass.base.yml -f eclipse-pass.nightly.yml up`
version: '3.8'

services:
  auth:
    env_file:
      - .eclipse-pass.nightly_env

  pass-core:
    image: ghcr.io/eclipse-pass/pass-core-main:0.3.0-SNAPSHOT@sha256:cc2e6227322833b1d8ba098f9bfd5e442b2bbe1228d8ff32b51de0fd23774448
    env_file:
      - .eclipse-pass.nightly_env

  pass-ui:
    env_file:
      - .eclipse-pass.nightly_env

  postgres:
    env_file:
      - .eclipse-pass.nightly_env

  pass-ui-public:
    env_file:
      - .eclipse-pass.nightly_env

  idp:
    env_file:
      - .eclipse-pass.nightly_env

  loader:
    env_file:
      - .eclipse-pass.nightly_env
