version: '3.8'

# Manages the nightly.eclipse-pass.org deploy
# `docker-compose -f eclipse-pass.base.yml -f eclipse-pass.nightly.yml up`
version: '3.8'

services:
  auth:
    env_file: .eclipse-pass.nightly_env

  pass-core:
    env_file: .eclipse-pass.nightly_env
    image: ghcr.io/eclipse-pass/pass-core:0.2.0-SNAPSHOT

  pass-ui:
    env_file: .eclipse-pass.nightly_env

  postgres:
    env_file: .eclipse-pass.nightly_env

  pass-ui-public:
    env_file: .eclipse-pass.nightly_env

  loader:
    env_file: .eclipse-pass.nightly_env
