# The assets container runs once to write the persistent volume data and then is complete
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    io.kompose.service: assets
  name: assets
spec:
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-k8s.yaml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: assets
    spec:
      containers:
        # - image: birkland/assets:2019-04-08_3.4@sha256:7ec44bd52d7cf635ad05a3f509cf7439e187b7768b8a05abae81b49744ec9d5f
        - image: oapass/assets:0.1.0
          name: assets
          resources: {}
          volumeMounts:
            - mountPath: "/data"
              name: assets-pvc
      restartPolicy: Never
      securityContext:
        fsGroup: 1000
      volumes:
        - name: assets-pvc
          persistentVolumeClaim:
            claimName: passdata
  backoffLimit: 4
