apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-k8s.yaml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: ftpserver
  name: ftpserver
spec:
  ports:
    - name: "21"
      port: 21
      targetPort: 21
    - name: "30000"
      port: 30000
      targetPort: 30000
    - name: "30001"
      port: 30001
      targetPort: 30001
    - name: "30002"
      port: 30002
      targetPort: 30002
    - name: "30003"
      port: 30003
      targetPort: 30003
    - name: "30004"
      port: 30004
      targetPort: 30004
    - name: "30005"
      port: 30005
      targetPort: 30005
    - name: "30006"
      port: 30006
      targetPort: 30006
    - name: "30007"
      port: 30007
      targetPort: 30007
    - name: "30008"
      port: 30008
      targetPort: 30008
    - name: "30009"
      port: 30009
      targetPort: 30009
    - name: "30010"
      port: 30010
      targetPort: 30010
  selector:
    io.kompose.service: ftpserver
status:
  loadBalancer: {}
