apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-k8s.yaml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: idp
  name: idp
spec:
  ports:
    - name: "4443"
      port: 4443
      targetPort: 4443
  selector:
    io.kompose.service: idp
status:
  loadBalancer: {}
