kind: PersistentVolume
apiVersion: v1
metadata:
  name: passdata
  labels:
    type: local
spec:
  storageClassName: shared
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data"